apiVersion: v1
kind: Service
metadata:
  name: service-backend
  labels:
    service: backend
spec:
  type: NodePort
  ports:
  - port: 8989
    nodePort: 30002
    protocol: TCP
  selector:
    app: backend
