apiVersion: v1
kind: ReplicationController
metadata: 
  name: hello-rc
spec:
  replicas: 1
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
        image: boyi/test-demo:latest
        imagePullPolicy: Always
        env:
        - name: PRJ_VERSION
          value: "v1.0"
        - name: PRJ_PORT
          value: "8989"
        ports:
        - containerPort: 8989
