apiVersion: v1
kind: Pod
metadata: 
  name: hello-pod
  labels: 
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-crt
    image: boyi/test-demo:latest
    #imagePullPolicy: IfNotPresent
    env:
    - name: PRJ_VERSION
      value: "v1.0"
    ports:
    - containerPort: 8080
